name: CI on Develop

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: zealousmacwan/client-management-ui
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},value=1.0.0

      - 
        name: print version
        run: |
          cat ${{ steps.meta.outputs.tags }}  
      - 
        name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          #major | feature | bug | alpha | beta | rc 
          current-version: ${{ steps.meta.outputs.tags }}
          version-fragment: 'bug'       

      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          target: development
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


